### ISSUE TITLE
The transaction was rejected by networkrules (16 mandatory script.....

### ISSUE THREAD

**Issue by sinkadam** [fyookball/electrum#38] opened 2017-08-03 12:01 UTC
Help needed or a noob
I want to transfer my bcc rom the wallet. after i sign it (2fa) i get the following message (see below). I got no idea what it means and also not how to solve it.

ERROR: The transaction was rejected by networkrules (16 mandatory-script-verify-flag-failed (signature must use sighash_Forkid
I really hope someone can help me out.
Thanks already

**Comment by janvac** [comment] 2017-08-03 12:17
i have the same problem...... 
ERROR: The transaction was rejected by networkrules (16 mandatory-script-verify-flag-failed (signature must be zero for failed CHECK(MULTI)SIG operation..

many thanks!

**Comment by fyookball** [comment] 2017-08-03 13:23
duplicate of https://github.com/fyookball/electrum/issues/6

**Closed by fyookball** 2017-08-03 13:23 UTC

**Comment by janvac** [comment] 2017-08-03 14:26
And are you able to help me? It does not work....

Sent from my Mobile Device

3. 8. 2017 v 15:23, fyookball <notifications@github.com>:

**Comment by sinkadam** [comment] 2017-08-03 14:35
Unfortunately I'm not able to help.
Do you know how to disable 2fa?

Op 3 aug. 2017 4:26 p.m. schreef "janvac" <notifications@github.com>:

**Comment by janvac** [comment] 2017-08-03 14:43
Yes, but still same....

Sent from my Mobile Device

3. 8. 2017 v 16:35, sinkadam <notifications@github.com>:

**Comment by sinkadam** [comment] 2017-08-03 14:45
If you can explain me how to disable 2fa.i will try when I'm home. If it
works I can let you know what steps I took

Op 3 aug. 2017 4:43 p.m. schreef "janvac" <notifications@github.com>:

**Comment by janvac** [comment] 2017-08-03 14:53
I have disabled during creating of new electron cash and i have used the seed form original electrum wallets... system asked me if i want to keep or disable 2fa...i flagged disable.. true is that this new still is marked up as an 2fa wallet, but do not want from me google auth...

Sent from my Mobile Device

3. 8. 2017 v 16:45, sinkadam <notifications@github.com>:

**Comment by sinkadam** [comment] 2017-08-03 15:08
I have the same... If I have a solution I will let you know.

Op 3 aug. 2017 4:53 p.m. schreef "janvac" <notifications@github.com>:

**Comment by janvac** [comment] 2017-08-03 15:11
Ok

Sent from my Mobile Device

3. 8. 2017 v 17:08, sinkadam <notifications@github.com>:

**Comment by janvac** [comment] 2017-08-04 08:01
Any news guys?

**Comment by sinkadam** [comment] 2017-08-04 08:38
Unfortunately not.. I've got an appointment Sunday with a friend who is
programmer.. I will ask him

Op 4 aug. 2017 10:01 schreef "janvac" <notifications@github.com>:

**Comment by janvac** [comment] 2017-08-04 08:39
Ok thanks lento us know!

Sent from my Mobile Device

4. 8. 2017 v 10:38, sinkadam <notifications@github.com>:

**Comment by fyookball** [comment] 2017-08-04 13:58
did you try new version 2.9.2? Also see "workaround 2fa" issue

**Comment by janvac** [comment] 2017-08-04 14:17
No where i can download? As for me i jave 2.9 version... i will check it..

Sent from my Mobile Device

4. 8. 2017 v 15:58, fyookball <notifications@github.com>:

**Comment by sinkadam** [comment] 2017-08-04 14:21
Hey,
I just downloaded the new version and it seem to work.. It's still
unconfirmed.. But this is a step forward :)
Thanks... Hope it will work for you as well

Op 4 aug. 2017 16:17 schreef "janvac" <notifications@github.com>:

**Comment by janvac** [comment] 2017-08-05 17:51
Hi guys,
Perfect job! Version doe work and payment sent!
Thanks!
Jan

Sent from my Mobile Device

4. 8. 2017 v 16:21, sinkadam <notifications@github.com>:
