### ISSUE TITLE
non-hexadecimal number found in fromhex() arg at position 6

### ISSUE THREAD

**Issue by pablomandado** [fyookball/electrum#724] opened 2018-06-06 01:17 UTC
I imported an old BTC wallet to electrum cash to recover the BCH and when I try sending them anywhere it gives an error message:

"non-hexadecimal number found in fromhex() arg at position 6".

**Comment by rt121212121** [comment] 2018-06-06 06:13
There's no worthwhile way to fix this without a reproduction case.  Unless you can provide a similar wallet with nothing in it, whether this one after it is swept in something that can import it, it is very unlikely anyone will be able to tell what is going wrong.

**Comment by pablomandado** [comment] 2018-06-06 06:14
It doesn't matter, I imported it directly on a different wallet and it worked fine there.

**Comment by rt121212121** [comment] 2018-06-08 06:44
Closing this due to lack of ability to reproduce the problem.

**Closed by rt121212121** 2018-06-08 06:44 UTC
