### ISSUE TITLE
Redundant 0-amount address in output / ElectronCash 3.1.2 (portable)

### ISSUE THREAD

**Issue by PhilCorner** [fyookball/electrum#573] opened 2018-02-25 15:25 UTC
Hi there

When I use "Pay to Many" option and then define several external to local wallet addresses, which utilize the full amount from input, the wallet creates transaction with extra address in outputs, but with 0 amount.

If in settings it is set to use change address -- then this redundant address is from change list.
If in settings it is set not to use change address -- then address from input is also added in outputs, but with zero amount.

Could you please add a check if provided address(-es) use the full amount -- then not to add any other addresses with 0-amount. This error appears only when "Pay To Many" is used (even when pay to many mode used to pay to one address), during normal usage in case full amount goes to one address, then there is no issue.

Thank you.
Regards,
Phil

**Comment by marceloneil** [comment] 2018-02-25 22:28
This seems like a duplicate of #469

**Closed** 2018-04-04 18:05 UTC
