### ISSUE TITLE
2.9.4 crashes instantly after I enter my password correctly

### ISSUE THREAD

**Issue by Austin17jm** [fyookball/electrum#283] opened 2017-11-23 17:04 UTC
I tried reinstalling and that didn't work. I'm not sure what to do next. Ideas?

**Comment by RiskSlayer** [comment] 2017-11-26 01:03
I am experiencing the same problem with both 2.9.3 & 2.9.4 today - Thanksgiving day (2 days ago) I was able to claim my BCH via the 2FA Electrum method outlined by DarkLordGMS in this forum including closing & opening the Electron Cash Wallet a xouple of times to confirm the BCH balance was showing properly.

I did not transfer any BCH out & confirmed with Block Exploring site Blockdozer.com that my BCH balance is still showing at my address on the ledger.

Thoughts?

**Comment by fyookball** [comment] 2017-11-26 01:40
@Austin17jm was yours a 2fa?
@RiskSlayer if  you followed 2fa steps you should be now on a standard wallet

**Comment by Austin17jm** [comment] 2017-11-26 01:43
yes

**Comment by RiskSlayer** [comment] 2017-11-26 12:46
@fyookball - Not fully tracking how your comment relates to my issue, but yeah I am now on a standard wallet.  Password encrypts wallet (unrelated to 2fa).  BTW - your App recognizes an incorrect password and does not shut down.  Last night, I used 9.2.3 and restored from seeds on another computer, and things looked good (I saw correct balances 12 hrs ago), but this morning, I am getting "Not Verified" in the wallet.

Thoughts?

**Comment by fyookball** [comment] 2017-11-26 15:15
@Austin17jm @RiskSlayer 
2fa was never supported. #41 describes how to move coins to a standard wallet.

@RiskSlayer I am not clear if you are now on a standard wallet or not.

**Comment by vpetoscia** [comment] 2017-11-26 20:54
I also get instant crash on 2.9.4, all other versions load fine. This is a none 2FA wallet.

**Comment by fyookball** [comment] 2017-11-27 03:02
@vpetoscia do you have non standard english characters in wallet name?  whats your wallet name if you dont mind

**Comment by Austin17jm** [comment] 2017-11-28 18:07
I was able to move my coins, thank you.

But 2.9.4 is unusable. I've tried reinstalling it several times but it simply crashes when I open it. I sent my coins on 2.9.2

**Comment by rjjerez** [comment] 2017-12-05 20:24
I have wallet 2.9.3 with 2fa
at the time of creating it
I do not generate the seed
created on November 10
received 0.31 BCC
now I can not spend them
the cash is withheld
and I can not reset because I do not have seed
please help me
I need to pay something

**Comment by rjjerez** [comment] 2017-12-05 20:25
the bcc that I have in the wallet are bought, it is not from the fork

**Comment by fyookball** [comment] 2017-12-11 12:29
#41 for all 2fa issues.

**Closed by fyookball** 2017-12-11 12:29 UTC
