### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 496: character maps to <undefined>

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#719] opened 2018-06-02 13:46 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash_gui\qt\installwizard.py", line 189, in on_filename
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash\storage.py", line 73, in __init__
  File "c:\python3.5.4\lib\encodings\cp1252.py", line 23, in decode

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 496: character maps to <undefined>
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.2  | Windows-10-10.0.17134 | standard | es_ES |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment] 2018-06-06 06:00
Duplicate of #711. The fix is merged already.

**Closed** 2018-06-12 02:14 UTC
