### ISSUE TITLE
Electron Cash 2.9.2 - Broadcast Issue - 200 USD Reward!

### ISSUE THREAD

**Issue by Regipl** [fyookball/electrum#134] opened 2017-08-19 15:54 UTC
I have a Electron Cash 2.9.2 wallet with an visible BCH balance on it.

Due the 2FA i am not able to send it to a different address as i am getting the standard error message about "SIGHASH FORKID"

I know the options with restoring/creating a new wallet using the SEED from the wallet but i lost the SEED. 
The only thing i have is the encrypted wallet.dat file which i can access with my password and a working google auth.

I can sigh the transaction but not broadcast...

**Comment by cryptodavid** [comment] 2017-08-19 16:26
Go to tools -->network-->and change the server, try electroncash.casharia.com
If is still not working try different server.

Good luck

**Comment by Regipl** [comment] 2017-08-19 16:39
I tried all solutions which are described online without success, so the answer for my problem is for sure more complicated :)

**Comment by verretor** [comment] 2017-08-19 17:43
2FA doesn't work with ElectronCash. Backup your wallet.dat file and try it with Electrum. Then recover your seed from there.

**Comment by Regipl** [comment] 2017-08-19 20:08
Backup not possible > no seed.

**Comment by verretor** [comment] 2017-08-19 20:47
I mean a backup of wallet.dat. Copy it somewhere else just in case something goes wrong.

**Comment by Regipl** [comment] 2017-08-19 20:55
Okay but what should i do in Electrum?

I had BTC between 27.07 and 02.08 in a 2FA Electrum Wallet and transferred than further.

**Comment by verretor** [comment] 2017-08-19 23:12
If you paste wallet.dat into Electrum folder, you can try recover the seed with your password.

**Comment by fyookball** [comment] 2017-08-19 23:13
have you looked at the 2fa thread? #41

**Comment by fyookball** [comment] 2017-08-20 02:10
going to close this , i am trying to keep all 2fa discussion in #41.   please read the suggestions there and post there to your result.

**Closed by fyookball** 2017-08-20 02:10 UTC

**Comment by verretor** [comment] 2017-08-20 03:02
Even if the issue is closed, I'd like to know if using the wallet.dat file in Electrum instead of ElectronCash is enough to recover the seed. As far as I know, it should work.

**Comment by past2017** [comment] 2017-10-03 03:05
@verretor have you get your BCH back? I have same issue as you, lost my seed but have wallet.dat and password, if some suggestion,please contact me zhdongbo@qq.com or zhangdongbo2009@gmail.com, thanks
