### ISSUE TITLE
offline signing android: tx input values missing from serialization for qr code

### ISSUE THREAD

**Issue by EdwardBitkan** [fyookball/electrum#166] opened 2017-09-13 09:09 UTC
1. Create a wallet in an offline Android phone as a cold wallet.
1. Create a wallet with the public key of the cold wallet above in an online Android phone as broadcasting wallet.
1. Send to the receiving address in broadcasting wallet (same as cold wallet) 0.002 BCH. The broadcasting wallet received and the balance is 0.002.
1. Send 0.0001 BCH to a new address with the broadcasting wallet to create an unsigned transaction.
1. Sign the unsigned transaction using the cold wallet. The status is "signing". After about 3 seconds the wallet App crashed. I tried many times and it crashed 100% .
1. Open network of the cold wallet phone and sync the transaction.
1. Close network of the cold wallet phone after it received the 0.002 BCH transaction.
1. Cold wallet sign the transaction in step 4 successfully.

I've tried many times and found that to sign transaction successfully the cold wallet have to sync the latest transactions. But the cold wallet should not connect network to sync transactions. Is it a bug?

**Comment by fyookball** [comment] 2017-09-13 17:43
worked for me.  what version of Electron Cash and what device?

**Comment by EdwardBitkan** [comment] 2017-09-14 02:37
version: 2.9.3
device: MI 5C, Huawei Honor 5A. I've tried in these two devices. Not work.

**Comment by fyookball** [comment] 2017-09-14 04:32
is it actually cold (offline) or just a watching address?  i only tested as watching but not actually offline

**Comment by fyookball** [comment] 2017-09-14 13:45
if it is truly offline, how are you transferring the signed tx from one device to the other?

**Comment by EdwardBitkan** [comment] 2017-09-15 00:06
It is actually cold and offline wallet. 
1. The broadcasting wallet show the raw transaction QR code. 
1. The cold wallet scan the QR code. 
1. Then there will be a "sign" button in the cold wallet and click it to sign. Then show the signed transaction in QR code. 
1. The broadcasting wallet scan the QR code of cold wallet.
1. Broadcast.

**Comment by tim-le** [comment] 2017-09-16 06:54
I chose electrum because of such great cold wallet solution, 
hope it can be fixed soon in next release

**Comment by molecular** [comment] 2017-09-16 12:21
can this be reproduced with desktop version? I'd like to help but never used android version. Also desktop is easier to debug for me.

**Comment by fyookball** [comment] 2017-09-16 15:12
no reports of it not working on desktop.   i will try the qr scan thing and see what my results are

**Comment by tim-le** [comment] 2017-09-17 00:54
desktop version :  "load transaction from file" works well offline. 
the crash happens during signing, I think the bug is not about "load transaction from qr code" or "load transaction from file"

**Comment by fyookball** [comment] 2017-09-17 01:01
@tim-le it crashes for you on desktop when signing?

**Comment by tim-le** [comment] 2017-09-17 01:38
@fyookball no. I was trying to reproduce the issue with desktop version, however, it works well.

**Comment by tim-le** [comment] 2017-09-17 02:19
I almost tested every android version, 
I have been waiting this bug to be fixed so long.

**Comment by fyookball** [comment] 2017-09-17 05:21
@tim-le the bug was just reported 4 days ago.

**Comment by molecular** [comment] 2017-09-17 08:03
I can reproduce the problem (using electron cash desktop version as "online wallet" and android version as "cold" wallet (using "airplane mode" to simulate the phone being offline).

Happens just as @tim-le describes: qr-scanning the unsigned tx with the android wallet works. TX is loaded fine. Crash happens at signing step (after pressing "sign" button).

Now I have to find out how to get to debug logs. @fyookball: I vaguely remember something about a debugging android version?

**Comment by molecular** [comment] 2017-09-17 08:12
I think I managed to capture the stacktrace of the "crash" using `adb logcat`:

```
09-17 10:08:27.712 19793 19816 I python  :  Traceback (most recent call last):
09-17 10:08:27.712 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/main.py", line 377, in <module>
09-17 10:08:27.712 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/lib/daemon.py", line 283, in init_gui
09-17 10:08:27.713 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/gui/kivy/__init__.py", line 62, in main
09-17 10:08:27.713 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/platform/build/dists/ElectronCash/private/lib/python2.7/site-packages/kivy/app.py", line 829, in run
09-17 10:08:27.714 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/platform/build/dists/ElectronCash/private/lib/python2.7/site-packages/kivy/base.py", line 502, in runTouchApp
09-17 10:08:27.715 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/platform/build/dists/ElectronCash/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 712, in mainloop
09-17 10:08:27.716 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/platform/build/dists/ElectronCash/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 457, in _mainloop
09-17 10:08:27.716 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/platform/build/dists/ElectronCash/private/lib/python2.7/site-packages/kivy/base.py", line 337, in idle
09-17 10:08:27.717 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/platform/build/dists/ElectronCash/private/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
09-17 10:08:27.717 19793 19816 I python  :    File "kivy/_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7180)
09-17 10:08:27.718 19793 19816 I python  :    File "kivy/_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7063)
09-17 10:08:27.718 19793 19816 I python  :    File "kivy/_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:6993)
09-17 10:08:27.719 19793 19816 I python  :    File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3054)
09-17 10:08:27.719 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/gui/kivy/uix/dialogs/tx_dialog.py", line 134, in <lambda>
09-17 10:08:27.719 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/gui/kivy/uix/dialogs/tx_dialog.py", line 138, in __do_sign
09-17 10:08:27.720 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/lib/wallet.py", line 1104, in sign_transaction
09-17 10:08:27.720 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/lib/keystore.py", line 114, in sign_transaction
09-17 10:08:27.721 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/lib/transaction.py", line 829, in sign
09-17 10:08:27.721 19793 19816 I python  :    File "/home/ubuntu/gitwork/electrum/.buildozer/android/app/lib/transaction.py", line 727, in serialize_preimage
09-17 10:08:27.722 19793 19816 I python  :  KeyError: 'value'
09-17 10:08:27.915 19793 19816 I python  : Python for android ended.
```

**Comment by EdwardBitkan** [comment] 2017-09-17 08:27
> This is consistent with the fact that it works when the wallet is synced (which it never should be, of course, because it's "cold").
@molecular Thank you. This should be the crash reason.

**Comment by molecular** [comment] 2017-09-17 08:27
unsynced desktop version (--offline mode) with same wallet signs the tx just fine, so it seems to be android-related.

**Comment by tim-le** [comment] 2017-09-17 08:32
@molecular yeah, it's android-related,  however this bug only in android electron cash,  android electrum is fine.

**Comment by molecular** [comment] 2017-09-17 08:35
suspicion: maybe when serializing the tx for qr-code, the input values aren't included, but when saving to file (which I used with the desktop test) they are?

**Comment by molecular** [comment] 2017-09-17 08:48
@tim-le: side-note: cash uses a signing-scheme based on segwit. I wouldn't be surprised if this was broken in electrum also for segwit transactions. Digging...

**Comment by molecular** [comment] 2017-09-17 09:08
I could confirm my suspicion that input values are not serialized/deserialized into/from the qr-code.

It works for "save tx vto file" / "load tx from file" in electron cash due to 8c4f3ad3c943b6a39b21744f89d7652d479f6f05 by @junderw

We need to do something similar for qrcode serialization/deserialization (these are the functions *serialize(..)* and *deserialize(..)* in transaction.py, I assume.

I'm sure these functions are used elsewhere, so because of potential side-effects, this is probably not straight-forward.

**Comment by molecular** [comment] 2017-09-17 09:19
@tim-le: another workaround (without using offline PC) might be to transfer the tx to the android cold wallet using a file. There is a floppy icon in the send dialog. I suspected it could be used to load a tx from file, but it doesn't seem to do anything. Anyone have any info on wether the android version can load a tx from file and if so how?

**Comment by molecular** [comment] 2017-09-17 09:20
@fyookball, @tim-le: can one of you change the title of this issue to something like "offline signing: tx input values missing from serialization for qr code"?

**Comment by fyookball** [comment] 2017-10-05 17:21
notes from conversation with @molecular 

 something about the signing scheme we use requires to have the values (amounts) of the inputs of a tx for signing it.  they're part of the signature now (with segwit and cash signing scheme), I guess.
This is not a problem for synced wallets because they know all those values or can ask server (those are the values of the previous outputs)

But offline wallets have noone to query and no utxo db to look at...so for offline signing, those values need to be included in the to-be-signed tx.

so the question becomes: what information is not getting into the QR.   it works when using a file to transfer the tx (save to file).  some guy implemented inclusion of the input values into the saved file 
 

https://github.com/fyookball/electrum/commit/8c4f3ad3c943b6a39b21744f89d7652d479f6f05
  
so, we'd have to do something similar for the qr codes some people use to transfer transactions to their offline wallets
 

yeah and there was a follow up to that as there was a typo
 

https://github.com/fyookball/electrum/commit/e8e37beeb46de6bba831a814c08187a921c55473 

I think I found out that the qr code uses the serialize() function (for encoding one) and the deserialize() function when scanning one. So this is where we could implement that (if no side effects due to other calls of those functions)

**Comment by molecular** [comment] 2017-10-11 09:57
Thanks to @loumiwhy for the code from #170 and @kenman345 for the referencing, but I don't think #170 fixes #166. The code from #170 needs a synced wallet to look up the input values, which is not available for offline wallets, which need to be able to sign transactions with no blockchain info available. We really need to include the input values into the serialization.

**Comment by Danconnolly** [comment] 2017-10-11 22:48
The current serialize() is the format used for tx in the bitcoin protocol. It is used to broadcast tx to the electrum servers for example. We can't change it. We would have to come up with some sort of extended serialization format.

**Comment by junderw** [comment] 2017-10-12 02:50
Basically, do the same hacky thing I did before, except encode the values somehow when making the QR:

https://github.com/fyookball/electrum/blob/49c2f1ebfd74528a08b802aa8bceb7cd65597b09/gui/qt/transaction_dialog.py#L148

and trying to grab the values when reading the QR here:

https://github.com/fyookball/electrum/blob/49c2f1ebfd74528a08b802aa8bceb7cd65597b09/gui/qt/main_window.py#L2027

You could just do something simple like `text = text + ':' + ','.join(values)` where values is the output of `values = [x['value'] for x in self.tx.inputs()]` and then in the second part, check data for r":(\d+,?)+$" via regex or something and if it matches, try to strip the values and re-insert them to the tx somehow...

**Comment by molecular** [comment] 2017-10-12 12:07
@junderw thanks for moving things here! I understand your solution, but think it can be improved.

I'm still looking to find a better place to store/read the values. There's more places than the ones you mention where this need to be done (see below). We'd have to do the same thing at least also in https://github.com/fyookball/electrum/blob/cash/gui/kivy/main_window.py (android gui) where also the qr code is parsed in on_qr and other functions.

--------

This code you mention:
https://github.com/fyookball/electrum/blob/49c2f1ebfd74528a08b802aa8bceb7cd65597b09/gui/qt/transaction_dialog.py#L148

for example in the end uses the `transaction.serialize()` function (the str() call results in __str__() to be called as can be seen here:

https://github.com/fyookball/electrum/blob/49c2f1ebfd74528a08b802aa8bceb7cd65597b09/lib/transaction.py#L503-L506

---------

similarly the other code you mention:

https://github.com/fyookball/electrum/blob/49c2f1ebfd74528a08b802aa8bceb7cd65597b09/gui/qt/main_window.py#L2027

in the end (through the call to tx_from_text() function) uses the `transaction.deserialize()` function:

https://github.com/fyookball/electrum/blob/49c2f1ebfd74528a08b802aa8bceb7cd65597b09/gui/qt/main_window.py#L1994

`transaction.deserialize()` is also used by the android gui code when reading a qr code here:

https://github.com/fyookball/electrum/blob/49c2f1ebfd74528a08b802aa8bceb7cd65597b09/gui/kivy/main_window.py#L306

-----------

So maybe `transaction.serialize()` and `transaction.deserialize()` would be better places to implement saving/loading of the input values?

Of course on the downside we'll have to make sure the additional info doesn't break any other uses of these functions (like in command.py, synchronizer.py)

What do you think?

**Comment by molecular** [comment] 2017-10-12 12:09
@Danconnolly I didn't read your comment until after I posted my previous one.

That's indeed a show-stopper for my idea if adding those values to the serialization ;-(.

How would you suggest to implement such "extended serialization format"?

**Comment by kenman345** [comment] 2017-10-12 13:35
Maybe I am not understanding this properly, but the issue is with the cold wallet not getting the inputs from the serialized transaction, why cant we have the cold wallet ask for these inputs and use a QR code to bring them in or generate those as files just like the unsigned transaction is, so that they can all be brought in. 

Am I missing something here?

**Comment by fyookball** [comment] 2017-10-12 15:52
@kenman345 offline signing works, just not QR code. I could be wrong but reading junderw's comments i dont think we need additional QR codes.

**Comment by molecular** [comment] 2017-10-12 19:06
@kenman345 no, you're not missing anything. Your suggestion is a bit cumbersome, though. We want to include those values right into the qr code that represents the transaction. Fiddling with another separate qr-code is cumbersome and not necessary, using files is beside the point in the context of this ticket, because the user wants to use a qr-code (his offline wallet is on android) and when files are used, that can already be done now with just saving the tx and loading it again from file. The values were alread added to the file encoded earlier. We "just" need to do this also for the qr-encoded version of transactions and are looking for the best way to do it.

**Closed** 2017-11-25 07:38 UTC
