### ISSUE TITLE
TypeError: initial_value must be str or None, not bytes

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#630] opened 2018-04-04 15:40 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\util.py", line 613, in run_with_except_hook
  File "C:\Users\eenho\AppData\Local\Temp\_MEI615002\electroncash_plugins\email_requests\qt.py", line 84, in run
    self.poll()
  File "C:\Users\eenho\AppData\Local\Temp\_MEI615002\electroncash_plugins\email_requests\qt.py", line 69, in poll
    msg = email.message_from_string(msg_data[0][1])
  File "email\__init__.py", line 38, in message_from_string
  File "email\parser.py", line 68, in parsestr

TypeError: initial_value must be str or None, not bytes
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.6  | Windows-10-10.0.16299 | standard | en_AU |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment] 2018-06-08 07:54
Duplicate of #578

**Closed by rt121212121** 2018-06-08 07:54 UTC
Labels: duplicate
