### ISSUE TITLE
payment request fails - payment requests are not working at the moment

### ISSUE THREAD

**Issue by ser** [fyookball/electrum#766] opened 2018-06-29 02:07 UTC
Payload to send to Electrum:

```{'params': {'amount': 0.0021651117760957575, 'expiration': 1212}, 'method': 'addrequest', 'id': 'c6cf406e-0c4b-4eb7-b3d2-1712a4d3a553'}```

Data received back from Electrum:

```{'error': {'message': 'Invalid parameters: string argument without an encoding', 'code': -32602}, 'result': None, 'id': '2fd03026-d1ba-49c0-b781-dd30ee758c8d'}```

This but looks similar to https://github.com/spesmilo/electrum/issues/3411 but it is not that simple, as with that patch electron-cash says:

```{'error': {'message': 'Invalid parameters: b\'\\xfc\\\'w|.W\\xeb\\xd5\\xa3u\\x8a\\xc3\\x81v\\x91\\x7f\\x9c"\\xa7\\xd1\' is not JSON serializable', 'code': -32602}, 'result': None, 'id': '9e20dac3-52ac-4ace-b2c2-51f5cf2087b6'}```

It looks roots of this issue are much deeper, unfortunately.

**Comment by cculianu** [comment] 2018-06-30 21:02
Hey man thanks for reporting.  I have to admit I never used this feature in electron cash -- but I'll investigate the issue.  It hopefully is something easy/stupid.

I've assigned it to myself and will look at it on Monday.

**Comment by ser** [comment] 2018-07-01 00:08
Thanks, I am preparing multi-coin electrum payment system and all major electrum-based wallets work, including electrum itself, electrum dash and electrum litecoin. Only electron cash has issues.

**Comment by ser** [comment] 2018-07-01 00:11
If it gets fixed, I will include electron cash into https://github.com/spesmilo/electrum-merchant

**Comment by cculianu** [comment] 2018-07-01 22:12
Awesome! I'll look at it tomorrow first thing in the morning. 👍

**Comment by cculianu** [comment] 2018-07-02 08:41
How do I reproduce this problem?

./electron-cash -v addrequest 0.003 --expiration 7200 -m "mam req ascd"

Works for me.  No exceptions or errors.

Can you give me some easy ways to reproduce it?  It would help a lot.

**Comment by marceloneil** [comment] 2018-07-02 12:49
There is an example payment request on here: http://docs.electrum.org/en/latest/merchant.html

Additionally it seems like he's using JSON-RPC to interact with the daemon, but correct me if I'm wrong @ser

**Comment by ser** [comment] 2018-07-03 00:49
Hi, thanks, I will create a scenario how to reproduce the issue.

**Comment by cculianu** [comment] 2018-07-08 15:14
Hey sorry to leave you hanging. My laptop died. I just managed to get my dev environment kind of working on windows this weekend.

I may hold off on looking at this until I get my laptop back from the shop Thursday..

**Comment by rnbrady** [comment] 2018-07-10 17:17
I'd like to offer a 1 BCH bounty, provided the fix can be released by end of coming weekend. Happy to pay in advance. Also looking for paid support to integrate to a Node app next week.

**Comment by rt121212121** [comment] 2018-07-11 00:31
I'll try and push a fix this evening (NZST) if no-one else has by then.

**Comment by marceloneil** [comment] 2018-07-11 03:19
I'm sorry @ser and @rnbrady, but I wasn't able to reproduce this issue (on 3.2 and 3.3). Here's what I did, maybe you guys can point to something I did wrong:

First I started the daemon (testnet) and loaded a random wallet:
```
$ electron-cash daemon --testnet start
starting daemon (PID 24268)
$ electron-cash daemon --testnet load_wallet -w ~/.electron-cash/testnet/wallets/digitalbitbox-testing
true
```
Then I found the password and port
```
$ grep "rpcpassword" ~/.electron-cash/testnet/config  
    "rpcpassword": "g4fUv9qBM7iv-lZy5C5Z1A==",
$ cat ~/.electron-cash/testnet/daemon 
(('127.0.0.1', 37721), 1531278263.954635)
```
And then I made the request
```
$ curl --data-binary '{"params": {"amount": 0.0021651117760957575, "expiration": 1212}, "method": "addrequest", "id": "c6cf406e-0c4b-4eb7-b3d2-1712a4d3a553"}' http://user:g4fUv9qBM7iv-lZy5C5Z1A==@127.0.0.1:37721
{"result": {"time": 1531278329, "amount": 216511, "exp": 1212, "address": "qqspnesgx6udrt4pw5l0lxreczhwfw028ccx80wxpj", "memo": "", "id": "13db5fe435", "URI": "bchtest:qqspnesgx6udrt4pw5l0lxreczhwfw028ccx80wxpj?amount=0.00216511", "status": "Pending", "amount (BTC)": "0.00216511"}, "id": "c6cf406e-0c4b-4eb7-b3d2-1712a4d3a553", "error": null}%
```

Maybe there is something different with my version of the JSON-RPC library? I'm using:
```
jsonrpclib-pelix      0.3.1        
```

It's weird though, because you said it worked for other versions of electrum...

**Comment by ser** [comment] 2018-07-11 06:30
I have additionally websockets activated if it changes anything?

**Comment by rt121212121** [comment] 2018-07-11 07:19
Why are we only seeing the responses from the server?  When the server sends these, it also prints an exception to stderr.  Run your electron cash server with --verbose, if you are not already seeing these.
```python
                    except BaseException as e:
                        import traceback, sys
                        traceback.print_exc(file=sys.stderr)
                        myself.send_error(500, str(e))
```

**Comment by ser** [comment] 2018-07-11 07:30
daemon says the same:

```
Invalid call parameters: <Fault -32602: Invalid parameters: string argument without an encoding>
```

**Comment by ser** [comment] 2018-07-11 08:03
BTW, ss you can see, after your recent commits error has changed.

**Comment by rt121212121** [comment] 2018-07-11 08:08
I reverted the commit, the error should be the same.

**Comment by rnbrady** [comment] 2018-07-11 15:03
@marceloneil when you call addrequest the result doesn't contain an index_url or request_url. In my current setup of 3.3 I get the same thing (and no error) after I removed the certificate config.

**Comment by marceloneil** [comment] 2018-07-11 15:08
@ser It still works for me on git head with python 3.5, weird!

```
$ python3.5 electron-cash daemon --testnet start
starting daemon (PID 2984)
$ python3.5 electron-cash daemon --testnet load_wallet -w ~/.electron-cash/testnet/wallets/digitalbitbox-testing 
true
$ curl --data-binary '{"params": {"amount": 0.0021651117760957575, "expiration": 1212}, "method": "addrequest", "id": "c6cf406e-0c4b-4eb7-b3d2-1712a4d3a553"}' http://test:test@test.1lab.me:7777
{"error": null, "id": "c6cf406e-0c4b-4eb7-b3d2-1712a4d3a553", "result": {"id": "63cc512c5f", "time": 1531321409, "memo": "", "exp": 1212, "URI": "bchtest:qrc2l2ng7a6j7rh7xqc0yl7h0hnewztpkvdrv2n947?amount=0.00216511", "amount (BTC)": "0.00216511", "amount": 216511, "address": "qrc2l2ng7a6j7rh7xqc0yl7h0hnewztpkvdrv2n947", "status": "Pending"}}
```

I also set up websockets with a valid cert, and that seems to be running according to netstat.

**Comment by marceloneil** [comment] 2018-07-11 15:10
@rnbrady So you aren't getting the same issue? Or do you get the same issue when you have the certificate config.

The index_url/request_url thing seems like a different issue though, can you open a new ticket for that (unless I'm misunderstanding it")

**Comment by rnbrady** [comment] 2018-07-11 15:25
@marceloneil my point is that you need certs configured in order to reproduce this bug. 

From a quick search the error `string argument without an encoding` seems to come from using the `bytearray()` function incorrectly. In `paymentrequest.py` all the uses of that function seem to be inside methods dealing with certs and sigs.

**Comment by marceloneil** [comment] 2018-07-11 15:48
Alright, I can recreate the issue now thanks @rnbrady

**Comment by marceloneil** [comment] 2018-07-11 18:06
Try out the PR @ser and @rnbrady. It should work with the test case you pointed out.

One thing you'll need to do is reset the url_rewrite parameter in the config. You can do this in one line:
```bash
electron-cash setconfig url_rewrite "$(electron-cash getconfig url_rewrite)"
```
and for testnet:
```bash
electron-cash setconfig --testnet url_rewrite "$(electron-cash getconfig --testnet url_rewrite)"
```

**Comment by ser** [comment] 2018-07-12 00:13
BTW, it would be cool if you could deploy this extension to the daemon as it makes payments much more convenient to use: https://github.com/spesmilo/electrum/blob/master/plugins/labels/cmdline.py

And another BTW: is label service for Electron Cash stable and running?

**Comment by rt121212121** [comment] 2018-07-12 07:24
Do we need someone to pull the trigger on merging the pull request?  We've had several reviews and user @ser has verified it fixes the problem.

**Closed** 2018-07-16 04:03 UTC
Labels: bug

**Comment by rnbrady** [comment] 2018-07-16 12:04
@rt121212121 thanks for work on this, please contact me on richard@trustless.io re bounty.

**Comment by rt121212121** [comment] 2018-07-16 19:04
I did no work.  It's all marcel.

**Comment by ser** [comment] 2018-07-19 02:07
https://github.com/spesmilo/electrum-merchant now supports Bitcoin Cash

**Comment by marceloneil** [comment] 2018-07-19 02:10
@ser how useful is labelsync? I'm not sure if it works or not, but I can investigate it

**Comment by ser** [comment] 2018-07-19 02:14
Extremely useful as you can keep all memo fields across instances and installations. Server is pretty simple and code is public, electrum uses your MPK to encrypt data before sending to the server.

**Comment by marceloneil** [comment] 2018-07-19 02:22
So like the cosigner pool?
