### ISSUE TITLE
BCH transaction error/return

### ISSUE THREAD

**Issue by tordommi** [fyookball/electrum#681] opened 2018-05-14 14:31 UTC
Hi,

A few hours ago I thought I had sent 1 BCH to legacy address 18cC12roA4MHZQjULXYgkZphu17rgi4iCC. This was a BCH Blender deposit.

However the output address (as far as I can tell) on my wallet transaction details is 1AetzhW7kj4L9TkmQKeqCeUi7uH4Ks6zh8

The transaction page on BCH Blender says 'waiting for deposit'. I thought the transaction was finished though, it has 25 confirmation.

All I did was copy and paste the legacy address.
Have I sent it to the wrong address?
Can I get the payment returned to me?

Any help would be really appreciated.

**Comment by fyookball** [comment] 2018-05-14 14:55
duplicate of #680

**Closed by fyookball** 2018-05-14 14:55 UTC
