### ISSUE TITLE
Running electron cash on a raspberry pi 3

### ISSUE THREAD

**Issue by Olorin22** [fyookball/electrum#479] opened 2018-01-16 00:12 UTC
Hi there! 
I would like to set up an electron cash cold wallet in a raspberry Pi 3 computer. I intend to use the Rpi3 as the "offline computer", so it needs to be able to generate the (public, private) key pairs from a seed and sign transactions generated from an online "watch only" computer. 
Did someone ever try this and thus could provide me with some guiding lines?
I think this could be very nice for our community, as it looks like mainstream "hardware" wallet retailers like ledger are screwing everyday users of BCH by censoring small fees BCH microtransactions ( i've personally experienced this). This is unacceptable and we need to empower BCH users with a cheap, reliable, ultra secure coin vault. 
The steps I was trying to follow for my project: 
- First: test electron cash in any available computer environment to see if it does what I want it to do. I tried it with mac osx and managed, with some work and a lot of help from people here, to do offline signing of transactions. Since  it does the cold storage very well, I know this is the wallet i want to use on my Rpi3. Done! 
- Next step I figured out was to try it on an OS as close as possible to the final OS. As the final OS would be last stable version of raspbian I thought installing and running electron cash on my linux desktop would be pretty similar on doing the same things on raspbian. And I'm pretty much locked in here because:
 a/ I didn't manage to get electron cash to work properly on my linux mint 17.3 Cinnamon 64 bit version. I do manage to open it, create the wallets, but then when i try to open them it crashes and i get a message error in the terminal.
b/ I don't know if it's relevant to get it work on linux mint in order to be sure it will work on raspbian. 

So my questions are: Is the linux version of electron cash supposed to be compatible with raspbian? If yes, then can you help me in seting it up properly?  and if not, what could be done in order to make it compatible with raspbian. I'm ready to test and work with you guys in order to make this happen. So please give me a hand! Thanking you all in advance !

**Comment by marceloneil** [comment] 2018-01-16 00:51
I'm not sure how compatible electron cash is with ARM based systems (like the raspi), but it works on android so I'd assume you could get it to work without too many issues. I'm curious about what issues you were experiencing on linux mint, do you think you could provide the debug log? Also as a side note, electron cash supports the ledger hardware wallet (at least the nano S and blue).

**Comment by Olorin22** [comment] 2018-01-16 01:41
Thanks for the reply Marcel! 
Ok i will paste here the error log, but I'm curious about electron cash-ledger nano s pairing: do you mean that you can use the ledger nano S to send transactions through electron cash rather than using the ledger wallet app on chrome? If yes, I didn't knew it and I'm very eager to learn how to do that. Here is the log: 
./electron-cash ( last working command, opens the wallet generator and then) Traceback (most recent call last): File "./electron-cash", line 373, in <module> d.initgui(config, plugins) File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/daemon.py", line 304, in init_gui self.gui.main() File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/gui/qt/init.py", line 251, in main if not self.start_new_window(path, self.config.get('url')): File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/gui/qt/init.py", line 210, in start_new_window wallet.start_threads(self.daemon.network) File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/wallet.py", line 996, in start_threads self.synchronizer = Synchronizer(self, network) File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/synchronizer.py", line 55, in __init_ self.initialize() File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/synchronizer.py", line 186, in initialize self.subscribe_to_addresses(self.wallet.get_addresses()) File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/synchronizer.py", line 76, in subscribe_to_addresses hashes = [addr.to_scripthash_hex() for addr in addresses] File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/synchronizer.py", line 76, in <listcomp> hashes = [addr.to_scripthash_hex() for addr in addresses] File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/address.py", line 440, in to_scripthash_hex return hash_to_hex_str(self.to_scripthash()) File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/address.py", line 80, in hash_to_hex_str return bytes(reversed(x)).hex() AttributeError: 'bytes' object has no attribute 'hex'

hopefully you could help me a bit, thanks in advance !
P.S.: i got to go to bed, pretty late in here, so don't mind if I don't answer til i'm up tomorrow!

**Comment by marceloneil** [comment] 2018-01-16 01:49
@Olorin22 You need to use python 3.5 or higher, so if you're running something lower than that its likely the cause of your error.

Ledger wallet support is outlined here: https://github.com/fyookball/electrum/blob/master/plugins/ledger/README.md

**Comment by kyuupichan** [comment] 2018-01-16 09:45
Closing - you need more recent python

**Closed by kyuupichan** 2018-01-16 09:45 UTC

**Comment by Olorin22** [comment] 2018-01-16 14:19
python3.5 -V
Python 3.5.2

**Comment by marceloneil** [comment] 2018-01-16 14:35
Does running `python3.5 electron-cash` still give you the same error?

**Comment by Olorin22** [comment] 2018-01-16 14:55
I got this, even after having tried the suggestion in the end: 
olorin@holocron ~/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2 $ python3.5 electron-cash
Error: Could not import PyQt5 on Linux systems, you may try 'sudo apt-get install python3-pyqt5'

**Comment by marceloneil** [comment] 2018-01-16 14:56
You need to install pyqt5

**Comment by Olorin22** [comment] 2018-01-16 15:01
It is strange, in my software manager, it says that python3-pyqt5 ( Python 3 binding for qt5) is installed !

**Comment by marceloneil** [comment] 2018-01-16 17:49
Can you take a look at #477?

**Comment by fyookball** [comment] 2018-01-16 18:09
what command are you running to get the error above

**Comment by Olorin22** [comment] 2018-01-16 18:17
I'm pretty stuck here...i'm not managing to install pyqt5

**Comment by fyookball** [comment] 2018-01-16 18:21
what command did you use to get this:

File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/lib/daemon.py", line 304, in init_gui
self.gui.main()
File "/home/olorin/Desktop/Bitcoin et cryptos/COld storage/Electron Cash-3.1.2/gui/qt/init.py", line 251, in main

is this linux?

**Comment by Olorin22** [comment] 2018-01-16 18:22
I run ./electron-cash from the folder. Yes it is linux.

**Comment by fyookball** [comment] 2018-01-16 18:55
did you try python3 electron-cash

**Comment by Olorin22** [comment] 2018-01-16 18:59
python3 electron-cash
Traceback (most recent call last):
  File "electron-cash", line 373, in <module>
    d.init_gui(config, plugins)
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/lib/daemon.py", line 304, in init_gui
    self.gui.main()
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/gui/qt/__init__.py", line 251, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/gui/qt/__init__.py", line 210, in start_new_window
    wallet.start_threads(self.daemon.network)
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/lib/wallet.py", line 996, in start_threads
    self.synchronizer = Synchronizer(self, network)
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/lib/synchronizer.py", line 55, in __init__
    self.initialize()
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/lib/synchronizer.py", line 186, in initialize
    self.subscribe_to_addresses(self.wallet.get_addresses())
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/lib/synchronizer.py", line 76, in subscribe_to_addresses
    hashes = [addr.to_scripthash_hex() for addr in addresses]
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/lib/synchronizer.py", line 76, in <listcomp>
    hashes = [addr.to_scripthash_hex() for addr in addresses]
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/lib/address.py", line 440, in to_scripthash_hex
    return hash_to_hex_str(self.to_scripthash())
  File "/home/olorin/Desktop/Bitcoin et cryptos/Cold storage/Electron Cash-3.1.2/lib/address.py", line 80, in hash_to_hex_str
    return bytes(reversed(x)).hex()
AttributeError: 'bytes' object has no attribute 'hex'

**Comment by kyuupichan** [comment] 2018-01-16 23:25
https://docs.python.org/3.5/whatsnew/3.5.html

Shows hex() is in 3.5.  So somehow your invocation is not running 3.5
