### ISSUE TITLE
Gets stucked synchronizing  40 private keys

### ISSUE THREAD

**Issue by maxocoin** [fyookball/electrum#485] opened 2018-01-16 16:13 UTC
I created a wallet with 40 BTC private keys,  the transactions go back to 2013

After a while synchronizing (some times 2 minutes, sometimes 20 minutes) it throws an exception on the console and everything looks fine but I don't get any more notifications about new transactions coming in.

I left the Electrum open over night and it didn't finish the synchronization process.
The error in the console says:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/jdevora/Electron Cash-3.1.2/lib/network.py", line 959, in run
    self.wait_on_sockets()
  File "/home/jdevora/Electron Cash-3.1.2/lib/network.py", line 926, in wait_on_sockets
    self.process_responses(interface)
  File "/home/jdevora/Electron Cash-3.1.2/lib/network.py", line 614, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/jdevora/Electron Cash-3.1.2/lib/network.py", line 563, in process_response
    callback(response)
  File "/home/jdevora/Electron Cash-3.1.2/lib/synchronizer.py", line 153, in tx_response
    self.wallet.receive_tx_callback(tx_hash, tx, tx_height)
  File "/home/jdevora/Electron Cash-3.1.2/lib/wallet.py", line 755, in receive_tx_callback
    self.add_transaction(tx_hash, tx)
  File "/home/jdevora/Electron Cash-3.1.2/lib/wallet.py", line 690, in add_transaction
    assert isinstance(addr, Address)
AssertionError
```
Electron Cash Version 3.1.2
What can I do for further trouble shooting it?

**Comment by marceloneil** [comment] 2018-01-16 16:21
@fyookball this looks like an address formating issue with old transactions, possibly caused by the cashaddr update?

**Comment by kyuupichan** [comment] 2018-01-17 00:01
@maxocoin I think this is fixed in git head - please cofirm

**Closed** 2018-01-17 00:01 UTC

**Comment by maxocoin** [comment] 2018-01-18 01:35
Yes, I cloned the repository and build it and it works fine now.
Thank you
