### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#795] opened 2018-07-14 19:10 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app_packages/rubicon/objc/runtime.py", line 1065, in _objc_method
    result = f(py_self, *args)
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/appdelegate.py", line 44, in application_didFinishLaunchingWithOptions_
    ElectronCash.app.main()
  File "/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/app.py", line 31, in main
    gui.main()
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/gui.py", line 2112, in main
    self.setup_key_enclave(lambda: self.start_daemon())
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/gui.py", line 2081, in setup_key_enclave
    completion()
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/gui.py", line 2112, in <lambda>
    self.setup_key_enclave(lambda: self.start_daemon())
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/gui.py", line 1262, in start_daemon
    self.daemon = ed.Daemon(self.config, fd, True)
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash/daemon.py", line 133, in __init__
    self.init_server(config, fd, is_gui)
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash/daemon.py", line 148, in init_server
    os.write(fd, bytes(repr((server.socket.getsockname(), time.time())), 'utf8'))

OSError: [Errno 28] No space left on device
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.3 (iOS Build: 301)  | Darwin-17.6.0-iPhone8,2-64bit iOS 11.4 iPhone (967AA971-465B-4399-A4F9-A7777C9E3AFA) | unknown | en_UK |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2018-07-14 19:53
Dupe of #794

**Closed by cculianu** 2018-07-14 19:53 UTC
