### ISSUE TITLE
Opening bitcoincash: prefix from a URL causes error

### ISSUE THREAD

**Issue by sgbett** [fyookball/electrum#473] opened 2018-01-15 13:36 UTC
I updated a site to use the new bitcoincash prefix for a donation address eg

`<a href='bitcoincash:qzkhnlsarkfaz7653jt2rr29ek9fgzkx35huugd4t3'>bitcoincash:qzkhnlsarkfaz7653jt2rr29ek9fgzkx35huugd4t3</a>`

When I click on the URL, I'm asked if I want to allow this page to open Electron Cash, which I do but I then get the following error:

Invalid bitcoincash URI:
QByteArray.__contains__(): argument 1 has unexpected type 'str'

macOS High Sierra 10.13.1
Safari Version 11.0.1 (13604.3.5)
Electron Cash 3.1.2

**Comment by marceloneil** [comment] 2018-01-16 02:20
Hmm, it seems to work for me, maybe it's macos specific? Does electron cash crash, does a dialog popup or is it simply in the log?

**Comment by sgbett** [comment] 2018-01-16 02:30
Suspect macOS specific too.

Electron is fine it just pops up a dialogue that I can dismiss and go about my business...

<img width="852" alt="untitled 77" src="https://user-images.githubusercontent.com/1105029/34969137-34942c80-fa65-11e7-935c-c8aa8276d823.png">

**Comment by kyuupichan** [comment] 2018-01-16 11:30
I've pushed what I believe is a fix for this.  I hope someone who has this issue can try reproducing it from source.  My web browser doesn't attempt to open Electron Cash for some reason.

**Closed** 2018-01-16 11:29 UTC

**Comment by sgbett** [comment] 2018-01-16 11:55
going to attempt to build this to test (haven't done so before, fingers crossed!)

**Comment by marceloneil** [comment] 2018-01-16 14:22
Still works for me
