### ISSUE TITLE
Exception when wallet is closed after wallet storage device removed

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#624] opened 2018-03-29 20:22 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash_gui\qt\main_window.py", line 2912, in closeEvent
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash_gui\qt\main_window.py", line 2919, in clean_up
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\simple_config.py", line 131, in set_key
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\simple_config.py", line 140, in _set_key_in_user_config
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\simple_config.py", line 205, in save_user_config

PermissionError: [Errno 13] Permission denied: 'E:\\Electrum-Bitcoin\\electron_cash_data\\config'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.6  | Windows-10-10.0.16299 | standard | en_US |
| 3.2  | Windows-7-6.1.7601-SP1 | imported_privkey | es_MX |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment] 2018-06-20 06:43
Duplicate of #644

**Closed by rt121212121** 2018-06-20 06:43 UTC
