### ISSUE TITLE
TypeError: setCurrentIndex(self, int): argument 1 has unexpected type 'NoneType'

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#832] opened 2018-08-21 19:21 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/tmp/ec/ec-slp/gui/qt/main_window.py", line 89, in onPress
    self.func()
  File "/Users/calin/tmp/ec/ec-slp/gui/qt/main_window.py", line 3092, in settings_dialog
    addr_format_combo.setCurrentIndex(self.config.get("addr_format"))

TypeError: setCurrentIndex(self, int): argument 1 has unexpected type 'NoneType'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4  | 3.5.5 (default, Mar 29 2018, 16:22:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] | Darwin-17.7.0-x86_64-i386-64bit | imported_privkey | en_US |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2018-08-21 19:28
This is the SLP wallet.  I posted it to Dr. Venkman because I was having trouble reproducing it and it happened only once.

Steps to reproduce:

1. Open deterministic wallet
2. Click on settings
3. See crash..

If you toggle the "Address format" icon, the exception goes away and never happens again.

I'm going to investigate this now as i have the code open in front of my eyes.

Otherwise this is safe to ignore...

**Comment by bauerj** [comment] 2018-08-21 19:28
Indeed, this should be handled server-side. There should be some kind of escaping when formatting the issue text. Can you send a PR? I'm quite busy at the moment.☹️

**Comment by marceloneil** [comment] 2018-08-21 19:29
@bauerj I'm also pretty busy, I'll open one when I have the time haha.

**Comment by cculianu** [comment] 2018-08-21 19:57
I'm going to close this issue as i already fixed this on the SLP fork.. and it's noise from there. 

I'll post a PR referencing this issue to the crash reporter server side code github (if I can find it but I think bauerj is its master).

**Closed by cculianu** 2018-08-21 19:57 UTC
