### ISSUE TITLE
Can't Deserialise Double Spend Transaction

### ISSUE THREAD

**Issue by chrisall69** [fyookball/electrum#446] opened 2018-01-09 15:01 UTC
Using my electrum wallet I mistakenly sent BTC with too small fee, which remained unconfirmed (no confirmations at all) for a few days. To rectify this I sent to a different address with higher fee, so a deliberate double spend.

In electrum all looks good, no issues, but when I imported private keys into electron I have an issue with that transaction showing as 0 amount and the wallet will not synchronise. The offending address shows a minus amount https://blockchain.info/address/16yB3fctQNGYCfWPGmwETt3wqt8vxypZEX

This is the transaction, and the error in electron:

https://blockchain.info/tx/381bf924a97c8a7d2d5770ea44feec0eebc477b342ee8195a371b1c619efb113

electroncash.address.AddressError: compressed public keys are required
[Synchronizer] cannot deserialize transaction, skipping 381bf924a97c8a7d2d5770ea44feec0eebc477b342ee8195a371b1c619efb113

Any ideas how I can get electron to synchronise, like electrum does? Thank you

**Comment by kyuupichan** [comment] 2018-01-09 15:14
I don't understand - BTC and BCH split on 1st August, so your BTC transaction doesn't exist in BCH.

**Comment by chrisall69** [comment] 2018-01-09 16:01
Correct, but that address 16yB3fctQNGYCfWPGmwETt3wqt8vxypZEX had a balance before the split. The outputs of the later transaction include that address, and there is a BCH balance still there though the BTC is not:
https://blockchair.com/bitcoin/address/16yB3fctQNGYCfWPGmwETt3wqt8vxypZEX
https://blockchair.com/bitcoin-cash/address/16yB3fctQNGYCfWPGmwETt3wqt8vxypZEX

**Comment by chrisall69** [comment] 2018-01-09 16:12
https://blockchair.com/bitcoin/outputs?limit=100&q=transaction_id(215922527)&s=index(asc)
https://blockchair.com/bitcoin-cash/outputs?limit=100&q=transaction_id(215922527)&s=index(asc)

The issue is that electron shows that transaction as receiving 0

**Comment by kyuupichan** [comment] 2018-01-09 16:15
So what is the relevance of the recent BTC transactions you started out talking about?

I'm quite confused.

**Comment by kyuupichan** [comment] 2018-01-09 16:17
OK I can reproduce.  I'll take a look.  The only reason it's zero is because of the exception.

**Comment by kyuupichan** [comment] 2018-01-09 16:23
Fixed in git HEAD; balance now shows as      0.20472256

**Closed by kyuupichan** 2018-01-09 16:23 UTC

**Comment by chrisall69** [comment] 2018-01-12 03:43
Thank you, much appreciated, confirmed all working now.

Cheers,
