### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\~Bitcoins2\\electron_cash_data\\wallets'

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#679] opened 2018-05-14 05:18 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash_gui\qt\main_window.py", line 453, in new_wallet
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash_gui\qt\main_window.py", line 450, in get_wallet_folder
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash\simple_config.py", line 226, in get_wallet_path

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\~Bitcoins2\\electron_cash_data\\wallets'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.2  | Windows-10-10.0.16299 | imported_privkey | en_US |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment] 2018-05-27 06:59
Fixed in the linked commit.  Comment added so the issue is marked in the issues list.

**Closed** 2018-06-12 07:56 UTC
