### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\OneDrive\\Wallet\\ElectronCash\\electron_cash_data\\blockchain_headers'

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#669] opened 2018-05-09 17:51 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\util.py", line 613, in run_with_except_hook
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 960, in run
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 927, in wait_on_sockets
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 615, in process_responses
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 561, in process_response
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 868, in on_get_header
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\blockchain.py", line 285, in save_header
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\blockchain.py", line 270, in write

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\OneDrive\\Wallet\\ElectronCash\\electron_cash_data\\blockchain_headers'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.6  | Windows-10-10.0.16299 | standard | ru_RU |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment] 2018-05-27 07:42
Read permission denied on a file in a OneDrive directory.  I am not sure it's possible to know why this happened, or how to fix it.  Nothing similar has happened for Electrum.

@fyookball @marceloneil  My vote is that this be closed.

**Comment by rt121212121** [comment] 2018-06-08 08:07
Duplicate of #664

**Closed by rt121212121** 2018-06-08 08:07 UTC
Labels: duplicate
