### ISSUE TITLE
Which teh best form for Update Electron-Cash

### ISSUE THREAD

**Issue by mauromoises** [fyookball/electrum#267] opened 2017-11-18 00:45 UTC
I got it recovery my wallet from de Electron-Cash 2.9.3
But I ask what is the best way to update the wallet???
If I install the portfolio 2.9.4 in another machine and there I send my funds from the wallet 2.9.3 or some problem in continuing to use version 2.9.3 to send money???

**Comment by Devar** [comment] 2017-11-18 03:55
You won't be able to use 2.9.3. Recovering the same wallet onto another machine will show your balances immediately, no need to send anything.

**Comment by mauromoises** [comment] 2017-11-18 08:24
Hi, whats up friend.
Just to do that, it happened is that I just recovered my wallet and there were complications because I had 2FA, I used the seed to restore it and I detected 2FA and I had to disable it, if I use that same seed in version 2.9.4 it does not recognize me the seed and create a wallet with zero balance.
Hopefully someone with more experience help me
Are there problems with using version 2.9.3 so I can send exchanges or payments?
My wallet in version 2.9.3 is recovery i can see my funds.

**Comment by Sammium1** [comment] 2017-11-21 17:54
Hi Friends! 
I created wallet Electrum 3.0.2 16.NOV.2017. Got BitcoinCash on it (BHC). - but couldn't see them. 
To redeem my BHC - i downloaded ElectronCash, however cannot restore my wallet, as SEED entering doesn't activate NEXT button. -------- "Watch mode" can show my funds, but doesn't allow to use.
 
Does anybody heard solution of restoring Electrum 3.0.2 wallet with BHC(BitcoinCASH) at ElectronCash 2.9.4? 

The ISSUE is: Seed is absolutely correct and tested to recover Electrum on Electrum, But "NEXT" button remains inactive - as if seed was not valid. But i repeat - it's correct and tested in Electrum

When i add BIP39 -"NEXT" is activated, but wallet is EMPTY. 

Who knows what to do? Please share what you know.

**Comment by mauromoises** [comment] 2017-11-21 23:04
I had problems because I did not deactivate 2FA in the restoration of the wallet, and it seems that the problem continues to occur in version 2.9.4
I have restored the wallet in version 2.9.3 but I do not know if I can use it to send payments
Check if you have activated 2FA and disable it

**Comment by Sammium1** [comment] 2017-11-22 07:16
Thank you @mauromoises - worked out for me. I downloaded 2.9.3 - made restoration from Electrum to ElectronCash 2.9.3 and could see my Funds there. BUT, it didn't work out to open the wallet-file in 2.9.4. So I created new wallet in 2.9.4 and transferred funds from old 2.9.3 wallet to new 2.9.4.Regards. Alex.

**Comment by mauromoises** [comment] 2017-11-22 07:56
@Sammium1 I'm glad it worked for you.
But could you really do that?
Is that I'm stuck in that part, I already have my wallet restored in 2.9.3 I just do not know if I can use it to make payments or spend the funds
Can you confirm the proceeding of what you did?
Thank you so much

**Comment by Sammium1** [comment] 2017-11-22 08:30
@mauromoises Yes - exactly as described --- i also was afraid that 2.9.3 is not working well to send funds out, especially because it is RED - offline most of the time. So i sent 0,0055 BCH as TEST from 2.9.3 wallet to my NEW 2.9.4 wallet - transaction was "Unconfirmed" almost 6 minutes. Let me make print-screen for you - one in 2.9.3 and another in 2.9.4. PAY attention -- 2.9.3 is not connected most of it's time - wait till it comes online for a second to update info, before making your Transfer.
![untitled2 9 3](https://user-images.githubusercontent.com/33870935/33117109-3c4fdcd2-cfa2-11e7-913b-d21734f50222.jpg)
![untitled2 9 4](https://user-images.githubusercontent.com/33870935/33117110-3cb71d20-cfa2-11e7-8f39-64b571c6bc25.jpg)

**Comment by fyookball** [comment] 2017-11-25 01:14
#41 for 2fa issues.

**Closed by fyookball** 2017-11-25 01:14 UTC
