### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\electron_cash_data\\config'

### ISSUE THREAD

**Issue by ProfessorVenkman** [fyookball/electrum#721] opened 2018-06-03 14:01 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash_gui\qt\main_window.py", line 2912, in closeEvent
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash_gui\qt\main_window.py", line 2919, in clean_up
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash\simple_config.py", line 131, in set_key
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash\simple_config.py", line 140, in _set_key_in_user_config
  File "site-packages\electron_cash-3.2-py3.5.egg\electroncash\simple_config.py", line 205, in save_user_config

FileNotFoundError: [Errno 2] No such file or directory: 'F:\\electron_cash_data\\config'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.2  | Windows-10-10.0.16299 | standard | de_DE |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by rt121212121** [comment] 2018-06-07 08:04
Duplicate of #624

**Closed** 2018-06-08 06:45 UTC
