### ISSUE TITLE
Horrible low-res icon on OS X menu bar

### ISSUE THREAD

**Issue by gheemath** [fyookball/electrum#200] opened 2017-10-16 09:33 UTC
Very low res, minor, but should be fixed nonetheless

**Comment by gheemath** [comment] 2017-10-16 09:34
15" display if that matters

**Comment by fyookball** [comment] 2017-10-17 14:55
screenshot would be helpful as there are several icons.  it could be some issue with ico file

**Comment by gheemath** [comment] 2017-11-11 07:40
<img width="85" alt="1" src="https://user-images.githubusercontent.com/28027981/32687419-b95e6c34-c70f-11e7-8d88-691aaa89137e.png">

**Comment by yurkazaytsev** [comment] 2018-01-03 20:48
@gheemath do you have retina display or display with regular resolution?

**Comment by cculianu** [comment] 2018-01-09 16:56
I can help with this -- Jonald if you give me a higher rez icon I know how to make the Mac package use it on a retina display...

**Comment by stabwah** [comment] 2018-01-12 01:52
MacBook Pro Retina 15" 2013:
<img width="67" alt="screen shot 2018-01-12 at 12 51 20 pm" src="https://user-images.githubusercontent.com/35254939/34856119-76c162f6-f797-11e7-9c8a-3a79be79b4ac.png">

and Dark: <img width="64" alt="screen shot 2018-01-12 at 12 51 27 pm" src="https://user-images.githubusercontent.com/35254939/34856108-6de6228e-f797-11e7-8c35-4e44182a43ce.png">

**Comment by marceloneil** [comment] 2018-01-14 01:00
It seems to work fine on a 1024x768 mac vm
Light: ![light](https://user-images.githubusercontent.com/6353492/34911621-510fe4aa-f89c-11e7-8b5e-bb12f9bf33fb.png)
Dark: ![dark](https://user-images.githubusercontent.com/6353492/34911624-57c60392-f89c-11e7-8e9f-8f516cfbdfaa.png)
However, there seems to be no transparancy in the actual application icon: 
![black-background](https://user-images.githubusercontent.com/6353492/34911632-71b30ade-f89c-11e7-88e3-81974f9776b0.png)

**Comment by cculianu** [comment] 2018-01-14 09:16
You know -- all this time I thought it was supposed to look like that.

Hey @fyookball  -- what's the icon actually supposed to look like?  Like that? Or with a transparent background?  Let me know if it should be transparent as I think I can just replace the icon.rc file or whatever in the next build!

**Comment by fyookball** [comment] 2018-01-14 15:58
The "B" is supposed to be white, and the circle is supposed to be transparent.  The "black bars" on top and bottom also supposed to be transparent (actually not part of logo but if there is extra space in an image of that size it must be there to take up the space, so that would be transparent.   But sometimes when you view images on certain programs, transparent will show up as black.

@cculianu i will send you the image i have.

**Comment by cculianu** [comment] 2018-01-15 15:53
@gheemath please provide more information -- we are unable to reproduce this issue.

This also looks like it was on pre-Qt5 Electron Cash.  Qt4 was weird about icons on Mac.   I would say close this issue, @marceloneil / @fyookball

**Comment by fyookball** [comment] 2018-01-15 16:12
fixed

**Closed by fyookball** 2018-01-15 16:12 UTC
