### ISSUE TITLE
False incorrect password error

### ISSUE THREAD

**Issue by bjweichel** [fyookball/electrum#508] opened 2018-01-21 22:32 UTC
I imported keys into the ElectronCash for windows, which was successful and I was able to view my BCH.  After a couple of successful transfers, suddenly the password stopped working for sending.  I then started over by importing keys again, this time not encrypting the wallet, but the same problem cropped up after a couple of transfers.  The backup file had the same problem.  Luckily I was able to import my BCH into another application, but this is a very serious problem.

I did verify the SHA256 after downloading, and it matched, so this isn't a rogue version.  Downloaded on 1/17/18, version 3.1.2.

**Comment by fyookball** [comment] 2018-01-22 02:36
wallet files can get corrupted from time to time, but if this is more repeatable then its something i've not seen before.  if you can provide any steps to recreate i can try.

**Comment by bjweichel** [comment] 2018-01-22 03:12
It happened to me twice, after that I moved all my money out.  I started by importing 3 private keys, did a test send which worked, backed up the wallet, then some hours later attempted to send again and was told my password was incorrect.  The second time I did the same thing but in an unencrypted wallet.  For safety I have moved all the BCH (and pre-fork BTC) into other wallets, so I can't further test it.

**Comment by fortran77** [comment] 2018-01-24 12:35
I encountered this bug in two different wallets. I was able to reproduce it as given below. An example wallet that exhibits the bug is attached.  This password-protected encrypted wallet can be opened with the password, and addresses viewed, but trying to export the private keys or change the password yields an "Incorrect password" error.

The example wallet called test-2018-01-24 is attached here in a zip file (see at the end of this comment).

First, I generated 10 private keys by visiting the website

https://walletgenerator.net/?currency=BitcoinCash

and using the bulk wallet option.

![screenshot-0](https://user-images.githubusercontent.com/6755457/35331957-282f6c7a-00be-11e8-93f6-ff30a1844e53.png)

Using Electron Cash 3.1.2 on an Ubuntu 16.04.3 LTS system, I created a new wallet called "test-2018-01-24" with the option "Import Bitcoin addresses or private keys".

When prompted, on the "Import Bitcoin Addresses" screen, I pasted the 10 private keys from above into the entry box.

![screenshot-1](https://user-images.githubusercontent.com/6755457/35331982-45ab38b0-00be-11e8-94a3-3dfd96a9f02b.png)

The 10 private keys that were entered are listed below.

    5KiZsWbQrxNxFkVvmK53LYWt33umJHc3MchFcqVDC9m9QmNZV5f
    5Jvi9Qy4zKWan4jpzWEWv8BQAeJ4iuDYkuhyaHMuxLuF6Mt3PqS
    5KjbPFDydtB6eGrBG9gDqVjbXb9kmunPSegawnGyz1i4YSiZAvZ
    5K3Beyxc4AJ4ogWMfsmF5TBr4s6PKAyu3bVk8khUNjzUGvr8ji8
    5JVvitHTumoWQZbaZ6zhKNUqTsNhjr33Fd2G6FjjahJjRDGyN7q
    5KgZQuXbtoN7UhDtbvf4fuQjBtu6feEPipLXXNSVR6husDDgRyV
    5Jsuh7QAsnEesYkLRDaQu7ze2PxLXNdWKNcjPJkddLzpgt4jGRD
    5KZxbLN8i9C4a4ACWTcQeifsn6cB4NVcDzYCqABZtgvS3ze6o8P
    5KMvQGsxAUFsuEibZEVsMAGv6A91v4j1eY55TrA6hA1ZSszTBsa
    5KRV4vFe6Z2pLPg8erE9q3P7fTVqydsakgs5MEeeawyoR8dJ1qC

After clicking Next, when prompted, I used copy-and-paste to enter the below password into the entry boxes, and made sure that "Encrypt wallet file" was checked.

![screenshot-2](https://user-images.githubusercontent.com/6755457/35332076-95c34676-00be-11e8-84ac-4572ad88557b.png)

The password used was always:

    a.b.c.d.xxxxxxxxyyyyyyyy

This yielded a wallet containing 10 private keys that was password-protected, and encrypted, using the above password.

Now I proceeded to do a number of operations several times.

1. Wallet => Private keys => Export. (Entered password when prompted. Saw private keys in window. Canceled.)
2. Wallet => Password. (Entered password only once, clicked OK. This disabled password protection.)
3. Wallet => Password. (Entered password in all three boxes, clicked OK. This re-enabled password protection and encrypted the wallet.)
4. File => Exit.
5. Re-ran Electron Cash with the command line: `~/Electron\ Cash-3.1.2/electron-cash -w $PWD/test-2018-01-24`.

Repeated from step 1.

After doing the above operations a number of times (not always in exactly the same order), I ended up with a wallet file that is password-protected with the correct password, but yields a password error when I try to do either of the following operations:

Wallet => Private keys => Export
Wallet => Password.

The password being entered must be correct, because (a) I always used copy-and-paste to enter it and (b) I can open the wallet, and go to the Addresses screen and see the 10 addresses.

But trying to export the private keys or trying to change the password gives me an "Incorrect password" error.

[test-2018-01-24.zip](https://github.com/fyookball/electrum/files/1659796/test-2018-01-24.zip)

**Comment by fortran77** [comment] 2018-01-24 12:44
Probably the same bug as in #431 and #494. Maybe also #493.

**Comment by fortran77** [comment] 2018-01-24 13:09
Reading further, it appears that a fix has been [merged](https://github.com/fyookball/electrum/pull/449/commits/16c8f41ce85199e9679abcae96e673066dca42a2) already. The workaround given in the comment https://github.com/fyookball/electrum/issues/431#issuecomment-356908067 works in this case.

    wallet.keystore.update_password(None,'your password here')
    wallet.save_keystore()

**Closed** 2018-02-12 03:23 UTC
